export interface ListMachineryModel{
            machineSambaId: number,
            machineName: string,
            machinePlate: string,
            machineFuel: string,
            machineColor: string,
            machineBrand: string,
            machineType: string,
            machineAccumulatedHours: number,
            machineEngineOilChange: string,
            machineOilFilterChange: string,
            machineFuelFilterChange: string,
            machineHydraulicOilChange: string,
            machineDifferentialOilChange: string,
            machineFrontAxleLubrication: string,
            machinePlanetaryGearOilChange: string,
            machineRockerLubrication: string,
            machineFlannelLubrication: string,
            machineCrossheadLubrication:string
}